program: train.py
method: bayes  # grid, random, or bayes 중 선택 가능
metric:
  name: val_loss
  goal: minimize
parameters:
  optimizer:
    values: ['adam', 'sgd', 'rmsprop', 'adamw']
  lr:
    distribution: log_uniform
    min: 0.00001
    max: 0.1
  batch_size:
    values: [16, 32, 64, 128]
  weight_decay:
    distribution: log_uniform
    min: 0.00001
    max: 0.1
  dropout:
    distribution: uniform
    min: 0.0
    max: 0.5
  momentum:
    values: [0.9, 0.95, 0.99]
  scheduler:
    values: ['StepLR', 'CosineAnnealingLR', 'ReduceLROnPlateau']
  step_size:
    values: [10, 20, 30]
  gamma:
    values: [0.1, 0.5, 0.9]

command:
  - python
  - train.py
  - --config
  - /data/ephemeral/home/JSM_Secret_Code/configs/train_configs/train_module.yaml
  - --use_wandb

project: "B4_optimization_exp"