data_module: "src.data.custom_data_module.data_module.DataModule"

data_config_path: "/data/ephemeral/home/JSM_Secret_Code/configs/data_configs/data_module.yaml"
augmentation_config_path: "/data/ephemeral/home/JSM_Secret_Code/configs/augmentation_configs/data_augmentation.yaml"

models:
  - module: "src.plmodules.base_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results_simpleAug_CoAtNet_continue/fold_1/epoch=epoch=26-val_loss=val_loss=0.98-20240924-112213.ckpt"

  - module: "src.plmodules.base_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results_simpleAug_CoAtNet_continue/fold_1/epoch=epoch=28-val_loss=val_loss=0.98-20240924-112213.ckpt"

  - module: "src.plmodules.base_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results_simpleAug_CoAtNet_continue/fold_1/epoch=epoch=29-val_loss=val_loss=0.98-20240924-112213.ckpt"


model: 'CoAtNet3'


trainer:
  accelerator: gpu
  devices: 1

seed: 42  # 시드 값 추가
