data_module: "src.data.custom_data_module.data_module.DataModule"

data_config_path: "/data/ephemeral/home/JSM_Secret_Code/configs/data_configs/data_module.yaml"
augmentation_config_path: "/data/ephemeral/home/JSM_Secret_Code/configs/augmentation_configs/data_augmentation.yaml"

models:

  - module: "src.plmodules.base_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results_simpleAug/fold_1/epoch=epoch=18-val_loss=val_loss=0.98-20240922-172645.ckpt"
    weight : 1

  - module: "src.plmodules.base_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results_simpleAug/fold_1/epoch=epoch=21-val_loss=val_loss=0.98-20240922-172645.ckpt"
    weight : 1.3

  - module: "src.plmodules.base_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results_simpleAug/fold_1/epoch=epoch=25-val_loss=val_loss=0.98-20240922-172645.ckpt"
    weight : 1.5



model: 'EfficienNet B3'


trainer:
  accelerator: gpu
  devices: 1

seed: 42  # 시드 값 추가
