data_module: "src.data.custom_data_module.data_module.DataModule"

data_config_path: "/data/ephemeral/home/JSM_Secret_Code/configs/data_configs/data_module.yaml"
augmentation_config_path: "/data/ephemeral/home/JSM_Secret_Code/configs/augmentation_configs/data_augmentation.yaml"

models:
  - module: "src.plmodules.EfficientNetB3_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/B3_simpl_aug/epoch=epoch=9-val_loss=val_loss=1.44-20240925-161618.ckpt"
  
  - module: "src.plmodules.EfficientNetB3_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/B3_simpl_aug/epoch=epoch=11-val_loss=val_loss=1.43-20240925-161618.ckpt"

  - module: "src.plmodules.EfficientNetB3_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/B3_simpl_aug/epoch=epoch=12-val_loss=val_loss=1.43-20240925-161618.ckpt"

  - module: "src.plmodules.EfficienNetB7_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/B7_train_gen/epoch=epoch=2-val_loss=val_loss=1.57-20240925-161645.ckpt"

  - module: "src.plmodules.EfficienNetB7_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/B7_train_gen/epoch=epoch=4-val_loss=val_loss=1.58-20240925-161645.ckpt"

  - module: "src.plmodules.EfficienNetB7_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/B7_train_gen/epoch=epoch=5-val_loss=val_loss=1.60-20240925-161645.ckpt"

  - module: "src.plmodules.base_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/M3_simple_aug/epoch=epoch=22-val_loss=val_loss=1.43-20240925-161708.ckpt"

  - module: "src.plmodules.base_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/M3_simple_aug/epoch=epoch=23-val_loss=val_loss=1.42-20240925-161708.ckpt"

  - module: "src.plmodules.base_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/M3_simple_aug/epoch=epoch=24-val_loss=val_loss=1.43-20240925-161708.ckpt"

  - module: "src.plmodules.ViTTiny_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/ViT_simple_aug/epoch=epoch=10-val_loss=val_loss=1.46-20240925-161727.ckpt"

  - module: "src.plmodules.ViTTiny_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/ViT_simple_aug/epoch=epoch=11-val_loss=val_loss=1.45-20240925-161727.ckpt"

  - module: "src.plmodules.ViTTiny_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/ViT_simple_aug/epoch=epoch=12-val_loss=val_loss=1.45-20240925-161727.ckpt"

  - module: "src.plmodules.CoAtNet3_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/CoAtNetB3_simpleBlur_RGB_Norm/epoch=epoch=6-val_loss=val_loss=1.59-20240925-224814.ckpt"

  - module: "src.plmodules.CoAtNet3_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/CoAtNetB3_simpleBlur_RGB_Norm/epoch=epoch=7-val_loss=val_loss=1.54-20240925-224814.ckpt"

  - module: "src.plmodules.CoAtNet3_module.BaseModule"
    checkpoint: "/data/ephemeral/home/JSM_Secret_Code/epoch_results/CoAtNetB3_simpleBlur_RGB_Norm/epoch=epoch=8-val_loss=val_loss=1.55-20240925-224814.ckpt"


model: 'CoAtNet3'


trainer:
  accelerator: gpu
  devices: 1

seed: 14  # 시드 값 추가
