data:
  name: data
  raw_data_path: data/sketch
  processed_data_path: data/processed/sketch
  train_val_split: 0.8
  val_test_split: 0.7
  batch_size: 64
  num_workers: 7
  pin_memory: true
  k_folds: 3