augmentation:
  use_augmentation: false  # 데이터 증강 사용 여부
  transforms:
    - name: Resize
      params:
        size: [224, 224]
        
    - name: Normalize  # 정규화 추가
      params:
        mean: [0.485, 0.456, 0.406]  # ImageNet 평균값
        std: [0.229, 0.224, 0.225]   # ImageNet 표준편차값